### ISSUE TITLE
No title for pictures

### ISSUE THREAD

**Issue by letkan** [jlbelanger/galleri#38]
1. I can't figure out why the title I assign to pictures doesn't show.
2. Another bug I found is that after setup of the gallery the dot env file shows:
JSON_PATH=/home/user/photopublic/json instead of /home/user/photo/public/json
Same with UPLOADS_PATH

**Comment by jlbelanger** [comment]
Hi @letkan. By default, the image title is used for the image's alt text only. I'm currently working on replacing fslightbox with my own lightbox, and once that done, the image title will be displayed in the lightbox.

If you want to display the title with the image thumbnail though, you can use the `afterLoadImage` and `afterUpdateImage` callbacks to add a `<figcaption>` element for each image. This isn't a very obvious way to do it, so I'll probably make a change that will display the title by default.

``` js
function updateTitle($img, image) {
	const alt = image ? image.attributes.title : $img.getAttribute('alt');
	if (alt) {
		const $figure = $img.closest('figure');
		let $figcaption = $figure.querySelector('figcaption');
		let $span;

		if (!$figcaption) {
			$figcaption = document.createElement('figcaption');
			$figcaption.setAttribute('class', 'galleri-figcaption');
			$figcaption.setAttribute('aria-hidden', true);
			$figure.appendChild($figcaption);

			$span = document.createElement('span');
			$figcaption.appendChild($span);
		} else {
			$span = $figcaption.querySelector('span');
		}

		$span.innerText = alt;
	}
}

Galleri.default.init({
	callbacks: {
		afterLoadImage: ({ element }) => { updateTitle(element); },
		afterUpdateImage: ({ element, image }) => { updateTitle(element, image); },
	},
});
```

This is the SCSS used on the demo site to display the image title when hovering over the thumbnail:

``` scss
.galleri-figcaption {
	bottom: 0;
	left: 0;
	overflow: hidden;
	position: absolute;
	right: 0;
	z-index: 1;

	.galleri-is-admin & {
		bottom: $galleri-button-height;
	}

	span {
		background: rgba($galleri-darkest, .75);
		color: $galleri-lightest;
		display: block;
		line-height: 1.2;
		padding: $galleri-padding-mobile $galleri-padding-mobile #{$galleri-padding-mobile - 4px};
		transform: translateY(100%);
		transition: transform 200ms ease-in-out;

		figure:hover &,
		a:hover + &,
		a:active + &,
		a:focus + & {
			transform: translateY(0);
		}
	}
}
```

When running the setup script, you need to include a trailing slash (eg. `/home/user/photo/` instead of `/home/user/photo`). I'll try to make that more clear in the script.
